import { IActivity } from '@/redux/features/types';

export const activities: IActivity[] = [
  {
    id: 1,
    name: 'Afficher les prix',
    frequency: 4,
    duration: 10,
    priority: 'High',
    channelCluster: 1,
    tradeChannel: 1,
    status: false,
    category: 1,
  },
  {
    id: 2,
    name: 'Afficher les prix',
    frequency: 4,
    duration: 10,
    priority: 'High',
    channelCluster: 1,
    tradeChannel: 1,
    status: false,
    category: 2,
  },
  {
    id: 3,
    name: 'Afficher les prix',
    frequency: 4,
    duration: 5,
    priority: 'Medium',
    channelCluster: 1,
    tradeChannel: 1,
    status: false,
    category: 3,
  },

  {
    id: 4,
    name: 'Afficher les prix',
    frequency: 4,
    duration: 5,
    priority: 'Low',
    channelCluster: 1,
    tradeChannel: 2,
    status: false,
    category: 1,
  },
  {
    id: 5,
    name: 'Recouvrement',
    frequency: 4,
    duration: 10,
    priority: 'Medium',
    channelCluster: 1,
    tradeChannel: 2,
    status: false,
    category: 1,
  },
  {
    id: 6,
    name: 'Afficher les prix',
    frequency: 4,
    duration: 5,
    priority: 'High',
    channelCluster: 1,
    tradeChannel: 2,
    status: false,
    category: 3,
  },

  {
    id: 7,
    name: 'Vendre nouveau produit',
    frequency: 4,
    duration: 10,
    priority: 'High',
    channelCluster: 1,
    tradeChannel: 1,
    status: false,
    category: 1,
  },
  {
    id: 8,
    name: 'Vendre nouveau produit',
    frequency: 4,
    duration: 10,
    priority: 'High',
    channelCluster: 1,
    tradeChannel: 1,
    status: false,
    category: 2,
  },
  {
    id: 9,
    name: 'Vendre nouveau produit',
    frequency: 4,
    duration: 5,
    priority: 'High',
    channelCluster: 1,
    tradeChannel: 1,
    status: false,
    category: 3,
  },

  {
    id: 10,
    name: 'Vendre nouveau produit',
    frequency: 4,
    duration: 5,
    priority: 'High',
    channelCluster: 1,
    tradeChannel: 2,
    status: false,
    category: 1,
  },
  {
    id: 11,
    name: 'Vendre nouveau produit',
    frequency: 4,
    duration: 10,
    priority: 'Low',
    channelCluster: 1,
    tradeChannel: 2,
    status: false,
    category: 2,
  },
  {
    id: 12,
    name: 'Vendre nouveau produit',
    frequency: 4,
    duration: 5,
    priority: 'Low',
    channelCluster: 1,
    tradeChannel: 2,
    status: false,
    category: 3,
  },
];


export const priorities = [
  {
    id: "srfhi727i22983090hfjhshk&92", 
    name: "Low"
  }, 
  {
    id: "srfhi7276475dhkji2298309092", 
    name: "Medium"
  }, 
  {
    id: "srfhi7adfsyue$27i2298309092", 
    name: "High"
  }, 
]